language: python
python:
  - 2.7
  - 3.4
cache:
  - pip
install:
  - pip install -r test-requirements.txt
  - pip install -e .[tests]
script:
  - coverage run trial spreadflow_xslt
after_success:
  - coveralls
